### ISSUE TITLE
License is not clear from repository metadata

### ISSUE THREAD

**Issue by bd808** [gabrielchl/media-data-verification-tool#24]
There is not an obvious LICENSE or COPYING file in the repository declaring the [OSI approved license](https://opensource.org/licenses) that this application is distributed under. See https://wikitech.wikimedia.org/wiki/Help:Toolforge/Rules#Toolforge_rules for more details.

**Comment by gabrielchl** [comment]
Thanks for bringing that up. License file added with commit b6a1720.
